### ISSUE TITLE
Window Title has missing characters?

### ISSUE THREAD

**Issue by NullVoxPopuli** [mare-imbrium/canis#3] opened 2015-11-09 19:23 UTC
![image](https://cloud.githubusercontent.com/assets/199018/11044001/64182530-86ed-11e5-9fed-399462c09461.png)

This is in the alpmenu example

**Comment by mare-imbrium** [comment] 2015-11-10 05:08
Which characters are missing ? Can you tell me your environment ?

I opened the demo and am getting all characters.

![acreenshot](http://i64.tinypic.com/2wcjwug.jpg)

**Comment by NullVoxPopuli** [comment] 2015-11-10 12:59
How do I find out what characters those are supposed to be?

I'm using 

```
uname -a
Linux UbuntuAllegient 3.19.0-31-generic #36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
```

**Comment by NullVoxPopuli** [comment] 2015-11-10 13:04
also, rvm info:
```
 rvm:
    version:      "rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "5 months 3 days 20 hours 41 minutes 46 seconds ago"
    path:         "/home/lprestonsegoiii/.rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.2.1p85"
    date:         "2015-02-26"
    platform:     "x86_64-linux"
    patchlevel:   "2015-02-26 revision 49769"
    full_version: "ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]"
```

**Comment by mare-imbrium** [comment] 2015-11-11 03:41
At exactly which part do you think a character is missing ?
Compare to the screenshot i put.
Is the "u" in menu missing ? Or something else ?

Can you make your window larger before you invoke "ruby alpmenu.rb" ?
How come your screen dump is showing those funny characters around the words "Table demo"?

What is your TERM setting ?

**Comment by NullVoxPopuli** [comment] 2015-11-11 10:35
I guess good news, is that this is only on my Ubuntu virtual machine. My native Ubuntu doesn't have the issue. 
I'll report back soon with the VM's TERM setting

**Comment by NullVoxPopuli** [comment] 2015-11-11 14:45
```
$ echo $TERM
xterm-color
```

**Comment by NullVoxPopuli** [comment] 2015-11-11 22:49
same TERM on my desktop, too.
So something else is different between my VM and my desktop.

**Comment by fwolfst** [comment] 2016-01-12 19:02
Happens on my regular setup, too (echo $TERM -> xterm). I suppose it has something to do with the LC_TYPE/LANG/LANG_ALL env vars (utf8ish in my case) and canis/ffi-ncurse not picking them up correctly.

If I run boxed ffi-ncurses (not canis) examples directly everything seems to work.

**Comment by mare-imbrium** [comment] 2016-01-13 04:53
I am unable to understand exactly what is not working. Could you give me the exact example of an ffi-ncurses program that is displaying a title correctly, and what is missing in the canis title ? Are you referring to the junk characters coming in the title ?

I don't think canis is doing anything with the environment or terminal beyond what ffi has done. However, i do know that some changes had to be made when this codebase moved from using ncurses to ffi-ncurses. I also do know that things work differently in different TERM setting. Such as background for messageboxes, or underline.

**Comment by mare-imbrium** [comment] 2016-01-13 04:57
Perhaps you are referring to the **junk characters** coming in the title bar. They are actually spaces. But some TERM settings do some kind of optimisation so that blank spaces are not refreshed -- i cannot remember the exact details now. That is why clearing a `messagebox` is a big pain, you still sometimes see black lines on a white message box.

I will compare the code of the title in the table class with that of the form title and see how they differ since the table title does not show junk characters.

**Comment by mare-imbrium** [comment] 2016-01-13 04:59
$ echo $TERM                                                             ✖ ✱ ➜ ◼
screen-256color

Have you tried xterm-256color ?

**Comment by fwolfst** [comment] 2016-01-13 06:35
Thanks for looking into this.
I did now with
    export TERM=xterm-256color
    ruby alpmenu.rb
No change. And yes, I was referring to the "junk" characters in the title. Actually I have no ffi-ncurses app with titles, just the examples there "looked okay".

Funnily enough, the "weird character" also gets printed when I copy your command; note that otherwise I have no trouble in the terminal (and I use it quiet a lot):

![weird_chars_echo_term](https://cloud.githubusercontent.com/assets/219373/12286832/efb1f726-b9c7-11e5-86d3-1559933d7476.png)

**Comment by fwolfst** [comment] 2016-01-13 07:02
It seems to me that the "mvhline" call in applicationheader#refresh is the problem:

    @window.mvhline(@row, @col, 1, len) # garbage
    @window.mvhline(@row, @col, " ".codepoints.first, len) # better

I do not know how the desired output is supposed to look, so I attached a screenshot.

The issue here is that assumptions are made about how "character 1' is represented. Not understanding much of codepoints, terminal and encoding issues to me it looks as if this and similar assumptions are made at various other places (grep for hline, vline).

Probably the correct "fix" would also be to use FFI::NCurses::ACS_HLINE (as in other places).

![alpmenu_space](https://cloud.githubusercontent.com/assets/219373/12287245/52a94020-b9cb-11e5-8086-d50b33f4699a.png)

**Comment by mare-imbrium** [comment] 2016-01-13 07:03
oh, please don't copy those weird characters, they are coming from my zsh prompt customisations.

**Comment by fwolfst** [comment] 2016-01-13 07:04
@mare-imbrium I guess its worth another issue ("Do not refer to chtypes by numbers, use constants instead"). I might help you with half an hour of cleanups if you point me to the (ffi-)ncurses calls to look out for.

**Comment by mare-imbrium** [comment] 2016-01-13 07:07
It'll take me a while to get back into the code. I've been away for a few months. I'll start look into application header and compare it to others. 

If i could replicate the problem that would have helped.

**Comment by mare-imbrium** [comment] 2016-01-13 07:22
>  ("Do not refer to chtypes by numbers, use constants instead").
What exactly do you mean here? Can you point me to some code, and tell me what it should have been ?

**Comment by fwolfst** [comment] 2016-01-13 07:29
See above:

    @window.mvhline(@row, @col, 1, len) # garbage. iiuc "1" is not chtype
    @window.mvhline(@row, @col, FFI::NCurses::ACS_HLINE, len) # better

Basically one should not use hard-coded numbers (e.g. 1) for ncurses functions expecting a chtype. I guess. :) Instead use well-defined constants (e.g. FFI::NCurses::ACS_HLINE). I saw multiple occurences of that (`grep hline`, `grep vline`, ... I guess there are many more).

**Comment by mare-imbrium** [comment] 2016-01-13 07:43
> @window.mvhline(@row, @col, FFI::NCurses::ACS_HLINE, len) # better

This prints a dash (HLINE) throughout the title, whereas we want a space. I tried out your other suggestion, and am looking up the docs for codepoints. I hope it is not too new as far as ruby versions is concerned.

**Comment by fwolfst** [comment] 2016-01-13 07:46
I assume that there is a NCurses::FFI::SOMETHING for it.
Btw, feel free to contact me in private or tell me where I can find you via
IRC.

**Comment by mare-imbrium** [comment] 2016-01-13 07:55
I think the issue is that in many TERM setting, the space is just not printed as an optimization. Whatever was there remains there and only the characters written on top and freshened. That is why I had to use the `mvhline` method to print a clear area on the screen, instead of using it for a hline.

" ".codepoints.first evaluates to 32, the ascii value, so that means that "1" would evaluate to a "Ctrl-A" if that is how it is treated. I don't know from where I got the "1".

**Comment by mare-imbrium** [comment] 2016-01-13 09:06
Hi
You can contact me at this email. rahul2012@gmail.com.


I have tried registering and connecting to IRC once but was unable to :(.


On Wed, Jan 13, 2016 at 1:16 PM, Felix Wolfsteller <notifications@github.com
> wrote:

> I assume that there is a NCurses::FFI::SOMETHING for it.
> Btw, feel free to contact me in private or tell me where I can find you via
> IRC.
>

**Comment by mare-imbrium** [comment] 2016-01-13 13:19
I have made changes to a new branch 0.0.9
https://github.com/mare-imbrium/canis/tree/0.0.9

I have used the `" ".codepoints.first` (which seems to be like `ord`.)

Does this solve your problem completely, or are there still some cases where you get junk characters ?

**Comment by fwolfst** [comment] 2016-01-13 15:07
Looks good, but i will look at the examples and post screenshots, I am not
sure that everything looks as expected.

Thanks!

**Comment by fwolfst** [comment] 2016-01-13 16:46
I think at least these calls are probably problematic:

lib/canis/core/util/rcommandwindow.rb:        @window.mvhline 0,0,1,@width
lib/canis/core/system/window.rb:        mvwhline(r, col, 1, len)
lib/canis/core/widgets/divider.rb:        @graphic.mvvline(@row, @col, 1, @length)
lib/canis/core/widgets/divider.rb:        @graphic.mvhline(@row, @col, 1, @length)
lib/canis/core/widgets/scrollbar.rb:      @graphic.mvvline(@row+0, @col, 1, @length-0)
lib/canis/core/widgets/scrollbar.rb:      @graphic.mvvline(r, c, 1, sclen)
lib/canis/core/widgets/rmenu.rb:      @window.mvhline(0, 0, 1, len)

**Comment by mare-imbrium** [comment] 2016-01-14 03:50
thanks, i will look into these right away.

**Comment by mare-imbrium** [comment] 2016-01-14 06:14
>lib/canis/core/util/rcommandwindow.rb: @window.mvhline 0,0,1,@width
lib/canis/core/system/window.rb: mvwhline(r, col, 1, len)
lib/canis/core/widgets/divider.rb: @graphic.mvvline(@row, @col, 1, @length)
lib/canis/core/widgets/divider.rb: @graphic.mvhline(@row, @col, 1, @length)
lib/canis/core/widgets/scrollbar.rb: @graphic.mvvline(@row+0, @col, 1, @length-0)
lib/canis/core/widgets/scrollbar.rb: @graphic.mvvline(r, c, 1, sclen)
lib/canis/core/widgets/rmenu.rb: @window.mvhline(0, 0, 1, len)

I have changed all these to `" ".codepoints.first` , however, i have no way of testing this since the problem is not occuring at my end even though I have tried with various TERM settings.

Let me now how it goes. I am committing this to the 0.0.9 branch. Thx.

**Comment by fwolfst** [comment] 2016-01-14 07:07
As we discussed off-github, there are also issues for me with corners of borders. I can confirm that these are broken in ffi-ncurses (https://github.com/seanohalpin/ffi-ncurses/blob/master/examples/acs_chars.rb) already, so this is not a canis-issue.

**Comment by mare-imbrium** [comment] 2016-01-14 07:12
oh. Maybe you should open an issue in ffi-ncurses.
Meantime, I am just checking out the examples after having made these changes.

**Comment by fwolfst** [comment] 2016-02-05 06:55
As we discussed off-github, there are also issues for me with corners of borders. I can confirm that these are broken in ffi-ncurses (https://github.com/seanohalpin/ffi-ncurses/blob/master/examples/acs_chars.rb) already, so this is not a canis-issue.

**Comment by mare-imbrium** [comment] 2016-02-05 07:24
okay then i can close it.

Thanks.

**Closed by mare-imbrium** 2016-02-05 07:24 UTC
